In [ ]:
from IPython.core.display import display_html
display_html("<script>Jupyter.notebook.kernel.restart()</script>",raw=True)

In [1]:
from sys import path; path.insert(1,"../src");
import fubar; from importlib import reload; reload(fubar);

***
< [GMIT Data Analytics](https://web.archive.org/web/20201029063153/https://www.gmit.ie/computer-science-and-applied-physics/higher-diploma-science-computing-data-analytics-ict) | [Home](https://github.com/SeanOhAileasa) | [README](https://github.com/SeanOhAileasa/mls-scikit-learn-scipy-stats/blob/main/README.md) >

[![GMIT](https://github.com/SeanOhAileasa/SeanOhAileasa/blob/master/rc/gmit.png?raw=true)](https://web.archive.org/web/20201029063153/https://www.gmit.ie/computer-science-and-applied-physics/higher-diploma-science-computing-data-analytics-ict)

## Machine Learning & Statistics, Winter 21/22
### Due: last commit on or before December 19th, 2021
### Topic: [``scikit-learn``](https://nbviewer.jupyter.org/github/SeanOhAileasa/mls-scikit-learn-scipy-stats/blob/main/scikit-learn.ipynb)
***

Winter 21/22 assessment for the ``Machine Learning & Statistics`` module (5 Credits) of the ``Higher Diploma in Science in Computing (Data Analytics) (H.Dip)`` programme (75 Credits) at **Galway-Mayo Institute of Technology (GMIT)**.

***
## Instructions
***

- Overview of the ``scikit-learn`` Python library.


- Demonstrations of three interesting ``scikit-learn`` algorithms.


- Using plots and other visualisations to enhance the notebook for viewers.

<a id="top"></a>
***
## Table of Contents
***

## [Project Management](#ppm)

* [Outstanding](#outstanding) <br/><br/>
    * [DAY:20 - Due Date](#outstandingday20) <br/><br/>
* [Commit](#ppmCommit) <br/><br/>
    * [History](#ppmCommitHistory) <br/><br/>
* [Planning](#ppmPlanning) <br/><br/>
    * [Research](#ppmGettingStartedResearch) <br/><br/>
    * [Development](#ppmGettingStartedDevelopment) <br/><br/>
    * [Consistency](#ppmGettingStartedConsistency) <br/><br/>
    * [Documentation](#ppmGettingStartedDocumentation) <br/><br/>
* [Considerations](#considerations) <br/><br/>
    * [Coding Conventions](#codingConventions)

## [Abstract](#abstract)

## [Introduction](#introduction)

* [Classification](#classification) <br/><br/>
* [Regression](#regression) <br/><br/>
* [Clustering](#clustering) <br/><br/>
    * [K-Means Clustering](#clusteringKMeansClustering) &#x1F6A7; <br/><br/>
        * [``sklearn.cluster.KMeans``](#clusteringsklearnclusterkmeans)

## [Solution](#solution)

- &#x1F6A7;

## [Conclusion](#conclusion)

- &#x1F6A7;

## [Appendix](#appendix)

- &#x1F6A7;

***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Introduction](#introduction) | [Solution](#solution) | [Conclusion](#conclusion) | [References](#references) >
<a id="ppm"></a>
***
## Project Management
***

< [Table of Contents](#top) | [References](#references) >
<a id="outstanding"></a>
***
### Outstanding
***

< [Table of Contents](#top) | [References](#references) >
<a id="outstandingday20"></a>
***
###### DAY:20 - Due Date
***

- introductory blurbs about scikit-learn and each of the scikit-learn algorithms of interest require more depth and explanation [[commit](https://github.com/SeanOhAileasa/mls-scikit-learn-scipy-stats/tree/023bf6b96aca8dfb2ea833cba6fc6101b8f334ad)]

< [Table of Contents](#top) | [References](#references) >
<a id="ppmCommit"></a>
***
### Commit
***

In [1]:
%%script bash
date

01 Oct 2021 20:21:44


```python
"DAY:78 - [Notebook: scikit-learn]: (Last Commit) Introductory blurbs about scikit-learn and each of the scikit-learn algorithms of interest require more depth and explanation - revert [DAY:20,0). Commit proposes researching classification. This was a typo and should be clustering. (Introduction) Hacking the example code from the sklearn.cluster.KMeans documentation. Short blurb on the parameters of object KMeans (i. n_clusters and ii. random_state) and method fit which computes the k-means clustering. Two clusters specified and the attribute labels_ confirms this. Making a prediction using method predict passing two new points predicts associated cluster. Attribute cluster_centers returns what the KMeans algorithm took as the centre point of each cluster. (Propose) Plotting the dataset X separating the two clusters."
```

In [2]:
exit()

< [Table of Contents](#top) | [References](#references) >
<a id="ppmCommitHistory"></a>
***
###### History
***

In [1]:
%%script bash
git log

commit 60956a92a82d7c3be0b4000db1fe1586cca94034
Author: SeanOhAileasa <seanohaileasa@protonmail.com>
Date:   Thu Sep 30 21:10:53 2021 +0100

    DAY:79 - [Notebook: scipy-stats]: (Last Commit) i. Blank Jupiter notebook created and; ii. submitted GitHub repository URL to GMIT. (Abstract) Brief introductory blurb about the analysis of variance (ANOVA) and its application beyond comparing just two populations (t-test). (Propose) Researching t-tests and especially F-Ratios (central part of ANOVA) before proceeding.

commit 023bf6b96aca8dfb2ea833cba6fc6101b8f334ad
Author: SeanOhAileasa <seanohaileasa@protonmail.com>
Date:   Wed Sep 29 19:44:12 2021 +0100

    DAY:80 - [Notebook: scikit-learn]: (Last Commit) i. Blank Jupiter notebook created and; ii. submitted GitHub repository URL to GMIT. (Abstract) Introductory blurb about scikit-learn. (Introduction) Short blurb on each scikit-learn algorithms of interest: i. classification; ii. regression and iii. clustering. Classification thought of i

In [2]:
exit()

< [Table of Contents](#top) | [References](#references) >
<a id="ppmPlanning"></a>
***
## Planning
***

- Keeping in mind:

i) GMIT assessment submission marking scheme; and 

ii) impression given to someone who is looking at this repository, endeavour to provide direct evidence of each of the items listed in each category where applicable (``Research`` - ``Development`` - ``Consistency`` - ``Documentation``).

< [Table of Contents](#top) | [References](#references) >
<a id="ppmGettingStartedResearch"></a>
***
###### Research
***

- GMIT: **"Evidence of research performed on topic; submission based on referenced literature, particularly academic literature; evidence of understanding of the documentation for any software or libraries used."**

- Investigation of packages used as demonstrated by references, background information, and approach: References will be in the format:

```
[referenceNumber] authorNames, referenceTitle, locationWebsiteBookVideo, dateMonthYear.
```

- Demonstrating work complete with appropriate references and not just for the problem but for the level of understanding of the problem.

- Code commentary will include details of package, module, object (if applicable) to demonstrate understanding of software documentation and libraries used.

```python
# b_T_hird_P_arty-imports
from matplotlib.pyplot import plot
```
```python
# package matplotlib - module pyplot
plot(x,y)
```

< [Table of Contents](#top) | [References](#references) >
<a id="ppmGettingStartedDevelopment"></a>
***
###### Development
***

- GMIT: **"Environment can be set up as described; code works without tweaking and as described; code is efficient, clean, and clear; evidence of consideration of standards and conventions appropriate to code of this kind."**

- Clear, well-written, and efficient code with appropriate comments - using Jupyter Notebook markdown cells to summarise concise workings. 

- As much as possible use the ``Style Guide for Python Code`` [Guido van Rossum](https://web.archive.org/web/20201029095211/https://www.python.org/dev/peps/pep-0008/). Refer user-defined [Coding Conventions](#codingConventions).

< [Table of Contents](#top) | [References](#references) >
<a id="ppmGettingStartedConsistency"></a>
***
###### Consistency
***

- GMIT: **"Evidence of planning and project management; pragmatic attitude to work as evidenced by well-considered commit history; commits are of a reasonable size; consideration of how commit history will be perceived by others."**

- Git commit blurb to include number of days outstanding before deadline (if applicable).

- Commits to highlight changes made since the last commit so that reviews of the git history can demonstrate compartmentation of work into the different sections.

< [Table of Contents](#top) | [References](#references) >
<a id="ppmGettingStartedDocumentation"></a>
***
###### Documentation
***

- GMIT: **"Clear documentation of how to create an environment in which any code will run, how to prepare the code for running, how to run the code including setting any options or flags, and what to expect upon running the code. Concise descriptions of code in comments and README."**

- Include descriptions/plots of theoretical and practical aspects of the problem(s) - comments to be very concise for ease of readability.

- Descriptions of code requiring further explanation will be presented in Jupyter Notebook markdown cells prior to code execution.

< [Table of Contents](#top) | [References](#references) >
<a id="considerations"></a>
***
### Considerations
***

- Using the four listed categories (``Research`` - ``Development`` - ``Consistency`` - ``Documentation``) in an attempt to not only focus on programming but also look at the information (data) and manipulating the data and coming up with techniques.

- Sometimes the most complex algorithms are counter-intuitive but do work and have been proven to work. Sometimes only a few lines of code is required to complete a topic/section - endeavour to explain the development of the algorithm and the reasoning behind why/how the code works.

- Jupyter Notebook text formatting/presentation to be tidied up closer to the deadline (if applicable).

< [Table of Contents](#top) | [References](#references) >
<a id="codingConventions"></a>
***
###### Coding Conventions
***

- user-defined function / name (variable) - start with letters as follows

| Example       | Signify 		          |
| :------------ |:------------------------|
|	f        	|	user-defined function |
|	n        	|	name - no variables   |

***
## END

< [Table of Contents](#top) | [Introduction](#introduction) | [Solution](#solution) | [Conclusion](#conclusion) | [References](#references) >
<a id="abstract"></a>
***
## Abstract
***

- ``scikit-learn`` is for machine learning in ``python`` [1]

- for topical machine learning algorithms ``scikit-learn`` might not be the first port of call but at the same time even if using other packages typically would use the various helper methods in ``scikit-learn`` to clean up the dataset initially - can use for neural networks but this would typically be outsourced to a specific package such as ``tensorflow.keras`` [1]

- organised in six sections ``scikit-learn`` (spawned from ``scipy``) consists of built-in algorithms that are typically considered machine learning [2]

***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Solution](#solution) | [Conclusion](#conclusion) | [References](#references) >
<a id="introduction"></a>
***
## Introduction
***

- demonstrations of three interesting ``scikit-learn`` algorithms

< [Table of Contents](#top) | [References](#references) >
<a id="classification"></a>
***
### Classification
***

- typically thought of in terms of labelling data [2]

- could have a set of images containing single digits hand drawn with zero in one image and one in another - the labels put on these images might be the digit $0$ and the digit $1$ etc [2]

- shown a picture with a digit drawn a ``classification`` algorithm is used to determine the digit it represents [2]

![classification](https://github.com/SeanOhAileasa/SeanOhAileasa/blob/master/rc/mls/scikit/classification.png?raw=true)

***(Image) scikit-learn, "Machine Learning in Python," [scikit-learn.org](https://scikit-learn.org/stable), n.d..***

< [Table of Contents](#top) | [References](#references) >
<a id="regression"></a>
***
### Regression
***

- fitting a line to a set of points (maybe with a little bit of error) [2]

- two different lines used (red and green) to fit the black dots (might assume theres a little bit of error in some of the measurements) - essentially trying to reverse engineer a function [2]

- looking at a selection of inputs and their corresponding outputs from some process and trying to fit some sort of function to those points [2] 

![regression](https://github.com/SeanOhAileasa/SeanOhAileasa/blob/master/rc/mls/scikit/regression.png?raw=true)

***(Image) scikit-learn, "Machine Learning in Python," [scikit-learn.org](https://scikit-learn.org/stable), n.d..***

- essentially all of science can be looked at from this viewpoint [2]

- going back hundreds of years when looking at the planets/stars in the sky to determine a map of how all seem to move around with the conclusion that the earth is actually orbiting the sun (not the other way around) - looking up at the sky measuring where the planets/stars are then trying to come up with some sort of a model (a way of maybe predicting where different planets/stars would be in the sky at different times) is essentially performing ``regression`` [2]

- Newton and Kepler might have figured out that the orbits looked like an oval and by joining all the dots up predicted where the planets/stars are going to be - ``regression`` is a very old idea [2]

< [Table of Contents](#top) | [References](#references) >
<a id="clustering"></a>
***
### Clustering
***

- grouping like items together - ``clustering`` is closely related to ``classification`` [2]

- the iris dataset has three different iris and to ``cluster`` is to group together the points that appear to be related [2]

![clustering](https://github.com/SeanOhAileasa/SeanOhAileasa/blob/master/rc/mls/scikit/clustering.png?raw=true)

***(Image) scikit-learn, "Machine Learning in Python," [scikit-learn.org](https://scikit-learn.org/stable), n.d..***

< [Table of Contents](#top) | [References](#references) >
<a id="clusteringKMeansClustering"></a>
***
###### K-Means Clustering
***

&#x1F6A7;

< [Table of Contents](#top) | [References](#references) >
<a id="clusteringsklearnclusterkmeans"></a>
***
###### ``sklearn.cluster.KMeans``
***

- analysing example code from ``sklearn.cluster.KMeans`` documentation [3]

In [1]:
import sklearn.cluster as skcl

In [2]:
print("\n".join(skcl.KMeans.__doc__.split("\n")[146:158]))

    >>> from sklearn.cluster import KMeans
    >>> import numpy as np
    >>> X = np.array([[1, 2], [1, 4], [1, 0],
    ...               [10, 2], [10, 4], [10, 0]])
    >>> kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    >>> kmeans.labels_
    array([1, 1, 1, 0, 0, 0], dtype=int32)
    >>> kmeans.predict([[0, 0], [12, 3]])
    array([1, 0], dtype=int32)
    >>> kmeans.cluster_centers_
    array([[10.,  2.],
           [ 1.,  2.]])


In [3]:
import numpy as np

- collection of data [13]

In [4]:
X=np.array(object=[[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]]) # numpy 6-d array

In [5]:
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [6]:
type(X)

numpy.ndarray

In [7]:
X.shape

(6, 2)

- such algorithms have a ``randon_state`` built-in (initialise some values internally within the algorithm using randon values - typically from a normal/uniform distribution randomly) [3]

- ``randon_state=0`` so that everytime the algoritm is run will get the same randon values initially [3]

In [8]:
nInsObjKMeans=skcl.KMeans(n_clusters=2,random_state=0)

- method ``fit`` computes ``KMeans`` clustering (performs the ``KMeans`` algorithm on the training dataset) [3]

In [9]:
nInsObjKMeans.fit(X=X) # algorithm via X

KMeans(n_clusters=2, random_state=0)

- each ``X`` element is a point [13]

In [10]:
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [11]:
X[5] # last X element

array([10,  0])

- two clusters already specified (the first three elements is a cluster and the second three elements is a cluster) [3] 

In [12]:
nInsObjKMeans.labels_

array([1, 1, 1, 0, 0, 0])

- method ``predict`` passed two new points (making a prediction) [3]

- ``[0,0]`` fits into the first class (``[1, 2],[1, 4],[1, 0]``) [3]

- ``[12,3]`` fits into the second class (``[10, 2],[10, 4],[10, 0]``) [3]

In [13]:
nVals=np.array([[0,0],[12,3]])

In [14]:
type(nVals)

numpy.ndarray

In [15]:
nPredictions=nInsObjKMeans.predict(nVals)

In [16]:
nPredictions

array([1, 0])

- the point ``[10.,  2.]`` is what the ``KMeans`` algorithm took as the centre point of one of the clusters (other cluster has a centre point of ``[ 1.,  2.]`` [3]

In [17]:
nCentre=nInsObjKMeans.cluster_centers_

In [18]:
nCentre

array([[10.,  2.],
       [ 1.,  2.]])

In [19]:
exit()

***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Introduction](#introduction) | [Conclusion](#conclusion) | [References](#references) >
<a id="solution"></a>
***
## Solution
***

&#x1F6A7;

<!-- - refer [Appendix](#appendix-df) to view the full dataset <a id="go-back-df"></a> -->
<!-- print(fGetModuleType(___x___),fDocumentation(___x___)) -->
***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Introduction](#introduction) | [Solution](#solution) | [References](#references) >
<a id="conclusion"></a>
***
## Conclusion
***

&#x1F6A7;

***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Introduction](#introduction) | [Solution](#solution) | [Conclusion](#conclusion) | [References](#references) >
<a id="references"></a>
***
## References
***
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1] I. McLoughlin, "Introduction to sklearn," GMIT, October 2018.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2] I. McLoughlin, "Overview of scikit-learn," GMIT, November 2020.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[3] I. McLoughlin, "KMeans clustering," GMIT, November 2020.

***
## END

< [Table of Contents](#top) | [Abstract](#abstract) | [Introduction](#introduction) | [Solution](#solution) | [Conclusion](#conclusion) | [References](#references) >
<a id="appendix"></a>
***
## Appendix
***

***
## END

# END JUPYTER NOTEBOOK